### ISSUE TITLE
Site is flagged by Malware Bytes

### ISSUE THREAD

**Issue by Nefari0uss** [tkashkin/tkashkin.github.io#2]
Not sure why the site is flagged but it is: [Imgur](https://i.imgur.com/mME8LFX.png).

**Comment by tkashkin** [comment]
I guess it's due to .tk domain which can be registered for free. If so, nothing can be done.

I could have bought myself another domain, but I don't want because
* .tk is free
* .tk nicely matches short form of my nickname

**Comment by Nefari0uss** [comment]
Looks like you can report a false positive [here](https://forums.malwarebytes.com/forum/123-website-blocking/). Thought I'd give a heads up!

**Comment by tkashkin** [comment]
@Nefari0uss if you already have an account on their forum, can you please report a false positive yourself? If you do, leave a link to this issue in the post. Thanks.

**Comment by tkashkin** [comment]
Reported: https://forums.malwarebytes.com/topic/241657-false-positive-httpstkashkintk/

**Comment by Nefari0uss** [comment]
I was gonna make an account and post this weekend but it looks like you got to it before me. Cheers, hope it gets unblocked soon.

**Comment by tkashkin** [comment]
@Nefari0uss it should be whitelisted now.

**Comment by Nefari0uss** [comment]
It is. Cheers!
